/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_serialport_api_SerialPort */

#ifndef _Included_android_serialport_api_SerialPortEx
#define _Included_android_serialport_api_SerialPortEx
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_serialport_api_SerialPort
 * Method:    open
 * Signature: (Ljava/lang/String;II)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_android_1serialport_1api_SerialPort_open
  (JNIEnv *, jclass, jstring, jint, jint);


/*
 * Class:     android_serialport_api_SerialPort
 * Method:    openIO
 * Signature: (Ljava/lang/String;I)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_android_1serialport_1api_SerialPort_openIO
        (JNIEnv *, jclass, jstring, jint);


/*
 * Class:     android_serialport_api_SerialPort
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_android_1serialport_1api_SerialPort_close
  (JNIEnv *, jobject);


//直接用c语言操作设备
/*
 * Class:     android_serialport_api_SerialPort
 * Method:    openFile
 * Signature: (Ljava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_android_1serialport_1api_SerialPort_openFile
        (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     android_serialport_api_SerialPort
 * Method:    closeFile
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_android_1serialport_1api_SerialPort_closeFile
        (JNIEnv *, jobject, jlong);

/*
 * Class:     android_serialport_api_SerialPort
 * Method:    writeFile
 * Signature: (J[B)J
 */
JNIEXPORT jlong JNICALL Java_android_1serialport_1api_SerialPort_writeFile
        (JNIEnv *, jobject, jlong, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
